version: '3.1'

services:
  flow:
    container_name: flow
    image: totalplatform/flow:latest
    volumes:
      - ##FOLDER_WWW##/flowstream:/www/.src/flowstream/
      - ##FOLDER_WWW##/databases:/www/.src/databases/
      - ##FOLDER_WWW##/private:/www/.src/private/
    environment:
      - VIRTUAL_MAX_UPLOAD=##MAXUPLOAD##
      - VIRTUAL_HOST=##HOST##
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=##HOST##                              # remove for localhost
      - DISABLE_ACCESS_LOGS=1

networks:
  default:
    name: proxy
    external: true
